typography_spectrum: 0.9983892121817917
color:
  brandStrength: 0.8609612626023591
  lightness: 0.1428663288243115
  saturation: 0.8725567050278187
  rhythmicContrast: 0.9956284170038998
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.08452659635804594
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7e36668-9745-4d0f-81fc-80fb23159762.png
name: 3rdiartndesign
title: my wheelhouse
